config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  post 'ideas/new'
  post 'ideas/create'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :idea_content, length: { minimum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hello_world_controller.rb
# frozen_string_literal: true

class HelloWorldController < ApplicationController
  layout "hello_world"

  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def new
    @idea = Idea.new
  end

   def index
    @ideas = Idea.all
  end

  def create
    @idea = Idea.new(idea_params)
    @idea.save
    redirect_to root_path
  end

  def find
    @idea = Idea.new
  end

  def show
  end

private

  def idea_params
    params.require(:idea).permit(:idea_content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorldApp", props: @hello_world_props, prerender: false) %>

app/views/ideas/create.html.erb
<h1>Ideas#create</h1>
<p>Find me in app/views/ideas/create.html.erb</p>

app/views/ideas/new.html.erb
<h1>Ideas#new</h1>
<p>Find me in app/views/ideas/new.html.erb</p>

app/views/ideas/show.html.erb
show.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dojo idea machine</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">

<!-- we should have 5 components -->

<!-- # 1 dropZone component -->

  <%= react_component("DropZone", props: @hello_world_props, prerender: false) %>

<!-- # 2 inputField component -->

  <div class="idea-bucket">
      <%= simple_form_for Idea.new, url: ideas_create_path do |f| %>
        <%= f.input :idea_content %>
        <%= f.button :submit %>
      <% end %>
  </div>

  <!-- # 3 ideaParameters component -->


  <!-- # 4 ideaList component -->

  <div class="idea-board">
     <ol>
      <% Idea.all.each do |idea| %>
        <li><%= idea.idea_content %></li>
      <% end %>
    </ol>
  </div>

<!-- # 5 ideaListItem component -->


<!-- # 6 generateButton component -->


</div>